### ISSUE TITLE
Libraries, dependencies & integrations

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/template-project-cpp#1]
From @martinjrobins original post.

#### Libraries:
- [x] Boost
- [ ] OpenMP (this is linked, but I still want to setup a test that uses openmp)

#### Dependencies:
- [x] CMake
- [x] Catch2

#### Integrations:
- [x] travis-ci (with linux and mac)
- [x] codecov
- [x] appveyor

#### A few other suggestions:
- [x] clang-format
- [x] clang-tidy (put in a config file, but need to actually use it)

**Comment by martinjrobins** [comment]
Thanks for this. I'm thinking about dropping eigen and vtk to stop the cmakelists file getting too verbose, leaving just boost and openmp.

I've tried using modern cmake, except for the dependencies. You are supposed to import these as targets now, but many finders don't support this currently, so I'm thinking of sticking to manual including/linking.

I've put in a couple of clang-format and clang-tidy configs from old projects, but these need editing.

Everything is still in draft form and no-where near working, so I've also added a warning in the readme, in case someone stumbles on this repo and tries to use it.

**Comment by martinjrobins** [comment]
mostly there now. still need to get appveyor working, and put in an openmp test (e.g. sum all the primes from 0-1000). And not sure what to do with clang-tidy

**Comment by fcooper8472** [comment]
Clang tidy now integrated.  Can we add this in to the continuous integration somehow @martinjrobins?
Would be nice to build with clang tidy enabled, possibly even fail if warnings are emitted?

**Comment by martinjrobins** [comment]
I'd be happy to leave them as warnings for the moment, although we should enable clang tidy on travis. I kinda like the separation between warnings and errors (rather than treating warnings as errors).

**Comment by fcooper8472** [comment]
Agreed - I just wondered if there's an easy way to automate the running of it.

Something like an additional yellow badge on the repo if there are any warnings from a clang-tidy build?
No idea if that's possible.

**Comment by martinjrobins** [comment]
I've removed the openmp stuff, I don't think it adds much, and is a pain to get working due to flaky cmake find routine, happy with this @fcooper8472 ? If so then I think we can close this one .

**Comment by fcooper8472** [comment]
Yep, happy to ditch openmp.

Let's close this one now, but perhaps think about adding in some other common libs in the future (I think a lot of mathsy people ought to be using something like `Eigen`).
