### ISSUE TITLE
Travis not finding the correct compiler

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/template-project-cpp#12]
Both the clang and gcc travis builds have the following snippet in the output:

```bash
Setting environment variables from .travis.yml
$ export CXX=g++-5
$ export BUILD_TYPE=Debug
$ export CXX=g++
$ export CC=gcc
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

```bash
Setting environment variables from .travis.yml
$ export CXX=clang++-5.0
$ export BUILD_TYPE=Debug
$ export CXX=g++
$ export CC=gcc
$ g++ --version
g++ (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5
```

So we appear to be ending up with the same (old) gcc version, and I think this might be causing the spurious warnings we're getting related to #9.

**Comment by fcooper8472** [comment]
Progress (of a sort) - the intended compiler versions are now being used, although I have vandalised almost every other part of the travis config!

**Comment by martinjrobins** [comment]
yea, seems to be working now. I've re-added the mac test in the matrix.
