### ISSUE TITLE
Header file extension names

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/template-project-cpp#15]
At the moment we are using `.h` for headers and `.cpp` for implementations.

Catch is currently `.hpp`.  I think it would be useful to have complete consistency within the project.  My vote would be for changing all headers to `.hpp` (something about the filenames being the same length...), although I'm not strongly wedded to one or the other.

Your thoughts @martinjrobins?

**Comment by martinjrobins** [comment]
Yes, these should be `.hpp`. I think it is good to distinguish C and C++ header files, but I have a bad habit of defaulting to `.h`

This is fixed now, and I've added the header files to `CMakeLists.txt`, which I also forgot to do
