### ISSUE TITLE
Project to potentially base this off

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/template-project-cpp#2]
Jason Turner has a [cpp_starter_project](https://github.com/lefticus/cpp_starter_project) that's intended to have best practises for CMake, with travis, appveyor etc integrations.

Might save a bit of time to use some of this as a basis?

**Comment by martinjrobins** [comment]
yea, I need to re-learn cmake it seems.... :(

**Comment by martinjrobins** [comment]
got everything from this project that we need. I didn't like the way Jason was doing the warnings in cmake though, since they (the warning compile flags) should be global I think. The appveyor and codecov script was very handy though!
