### ISSUE TITLE
Update copyright info in files

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/template-project-cpp#4]
Some source files have copyright information that seems to differ from the license file - do these need updating?

**Comment by martinjrobins** [comment]
yup, probably. The LICENSE file was generated by github, the copyright in the source files was copied from Aboria (which was copied from Chaste). Probably use the latter

**Comment by fcooper8472** [comment]
OK - should possibly update the date from 2016 in that case, too - and for Aboria?

**Comment by martinjrobins** [comment]
yup :)

**Comment by fcooper8472** [comment]
Made a few more changes that merge the Oxford version with the GitHub one, and added a license to the `CMakeLists.txt`.
