### ISSUE TITLE
Codecov testing too many files?

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/template-project-cpp#7]
I've not used Codecov before, so probably one for @martinjrobins:

[This output](https://travis-ci.org/OxfordRSE/template-project-cpp/jobs/376433140) looks as though codecov is checking a whole bunch of files including
```
File '/usr/include/boost/exception/exception.hpp'
File '/usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp'
File '/usr/include/c++/5/bits/postypes.h'
```
Can we get it to analyse only our project files?

**Comment by martinjrobins** [comment]
more codecov errors: clang is not using ENABLE_COVERAGE, so codecov cannot find any reports

**Comment by martinjrobins** [comment]
not too worry, we only want codecov reports for gcc anyway, so forget the last comment. But I might change ENABLE_COVERAGE to Template_ENABLE_COVERAGE for consistancy

**Comment by martinjrobins** [comment]
fixed. Turned off gcov and used lcov to filter out files
